version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: "0.75"
        reservations:
          memory: 150M
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - API_URL=http://backend:8080/api
    expose:
      - "3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "0.50"
        reservations:
          memory: 20M
    expose:
      - "8080"
      # - GO_ENV=production - Use this pattern to make code based logic
    restart: unless-stopped
